spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_db?serverTimezone=Asia/Seoul
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    oauth2:
      client:
        #registration
        registration.naver.client-name : naver
        registration.naver.client-id: ${naver.client-id}
        registration.naver.client-secret: ${naver.client-secret}
        registration.naver.redirect-uri: http://localhost:8080/login/oauth2/code/naver
        registration.naver.authorization-grant-type: authorization_code
        registration.naver.scope: name,email
        #provider
        provider.naver.authorization-uri: https://nid.naver.com/oauth2.0/authorize
        provider.naver.token-uri: https://nid.naver.com/oauth2.0/token
        provider.naver.user-info-uri: https://openapi.naver.com/v1/nid/me
        provider.naver.user-name-attribute: response